- id: 10.1109/ICRA.2018.8463146
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8449910/8460178/8463146/0278-fig-1-source-large.gif
  extra-links:
    - type: source
      link: https://ieeexplore-ieee-org.libdb.njit.edu:8443/search/searchresult.jsp?searchWithin=%22Publication%20Number%22:8449910&searchWithin=%22Document%20Title%22:FireAnt:%20A%20Modular%20Robot%20with%20Full-Body%20Continuous%20Docks
    - type: preprint
      link: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8463146
  tags:
    - knowledge graphs

- id: doi:10.1371/journal.pcbi.1007128
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  repo: greenelab/meta-review
  extra-links:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
