- id: 10.1007/978-3-030-92790-5_28
  image: https://robotics.northwestern.edu/images/news-events/news-articles/2021/petras_news_2021.png
  extra-links:
    - type: source
    - link: https://link.springer.com/chapter/10.1007/978-3-030-92790-5_28
    - text: View the publication
    - type: preprint
      link: https://robotics.northwestern.edu/documents/publications/2021dars_pswissler.pdf
      text: View the paper
    - type: preprint
      link: https://www.youtube.com/watch?v=kOQ2upp8Y2g
      text: View the presentation
    tags: 
      - self-assembly
      - robot algorithm
      - bio-inspired


- id: 10.1109/IROS45743.2020.9341116
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/9340668/9340635/9341116/swiss1-p8-swiss-large.gif
  extra-links:
    - type: source
      link: https://ieeexplore.ieee.org/abstract/document/9341116/figures
      text: View the publication
    - type: preprint
      link: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9341116
      text: View the paper
    - type: preprint
      link: https://www.youtube.com/watch?v=GKR5wpANZkU
      text: View a quick video
    - type: preprint
      link: https://www.youtube.com/watch?v=J-hUORZm1nE
      text: View the presentation
  tags:
    - self-assembly
    - modular robots
    - robot mechanisms
    - bio-inspired


- id: 10.1109/ICRA.2018.8463146
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8449910/8460178/8463146/0278-fig-1-source-large.gif
  extra-links:
    - type: source
      link: https://ieeexplore-ieee-org.libdb.njit.edu:8443/search/searchresult.jsp?searchWithin=%22Publication%20Number%22:8449910&searchWithin=%22Document%20Title%22:FireAnt:%20A%20Modular%20Robot%20with%20Full-Body%20Continuous%20Docks
      text: View the publication
    - type: preprint
      link: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8463146
      text: View the paper
    - type: preprint
      link: https://www.youtube.com/watch?v=zhM36h7zM1A
      text: View the presentation
  tags:
    - self-assembly
    - modular robots
    - robot mechanisms
    - bio-inspired


