- id: 10.1109/ICRA.2018.8463146
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8449910/8460178/8463146/0278-fig-1-source-large.gif
  extra-links:
    - type: source
      link: https://ieeexplore-ieee-org.libdb.njit.edu:8443/search/searchresult.jsp?searchWithin=%22Publication%20Number%22:8449910&searchWithin=%22Document%20Title%22:FireAnt:%20A%20Modular%20Robot%20with%20Full-Body%20Continuous%20Docks
      text: View the publication
    - type: preprint
      link: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8463146
      text: View the paper
  tags:
    - self-assembly
    - modular robots
    - robot mechanisms
